"""SNAX-MODEL: kernel-agnostic, cycle-level model of the SNAX cluster."""

from .accel import (
    AccelConfig,
    Accelerator,
    AccelPort,
    elementwise_stub,
    reduce_stub,
)
from .cluster import Cluster
from .ctrl import (
    Adapter,
    Controller,
    ControllerConfig,
    CsrRead,
    CsrWrite,
    RegisterMap,
    Wait,
    command_from_dict,
    program_from_dicts,
    program_to_dicts,
    register_adapter,
)
from .dma import Dma, DmaConfig, DmaDescriptor, DmaPattern, check_descriptor
from .l2 import L2AccessError, L2Config, L2Memory, L2Resp
from .mem import (
    AddressMap,
    BankConflictError,
    BankReq,
    BankResp,
    L1Config,
    L1Memory,
    WordInterleaved,
)
from .sched import (
    Component,
    Phase,
    Scheduler,
    SimulationError,
    SimulationTimeout,
    Stateful,
)
from .streamer import (
    Fifo,
    Streamer,
    StreamerConfig,
    StreamerRegs,
    address_stream,
    lane_offsets,
)
from .xbar import HoldViolation, Port, Xbar

__all__ = [
    "AccelConfig",
    "AccelPort",
    "Accelerator",
    "Adapter",
    "AddressMap",
    "BankConflictError",
    "BankReq",
    "BankResp",
    "Cluster",
    "Component",
    "Controller",
    "ControllerConfig",
    "CsrRead",
    "CsrWrite",
    "Dma",
    "DmaConfig",
    "DmaDescriptor",
    "DmaPattern",
    "Fifo",
    "HoldViolation",
    "L1Config",
    "L1Memory",
    "L2AccessError",
    "L2Config",
    "L2Memory",
    "L2Resp",
    "Phase",
    "Port",
    "RegisterMap",
    "Scheduler",
    "SimulationError",
    "SimulationTimeout",
    "Stateful",
    "Streamer",
    "StreamerConfig",
    "StreamerRegs",
    "Wait",
    "WordInterleaved",
    "Xbar",
    "address_stream",
    "check_descriptor",
    "command_from_dict",
    "elementwise_stub",
    "lane_offsets",
    "program_from_dicts",
    "program_to_dicts",
    "reduce_stub",
    "register_adapter",
]
