"""Test session setup: write the generated scenario files first (D67).

scenarios/*/scenario.json, their .npy inputs and scenarios/clusters/*.json
are generated by scenarios/make.py and are not in git, and many tests read
them. They are written once, before any test is collected, in the process
that runs the session; pytest-xdist workers find them already written.
"""

import importlib.util
from pathlib import Path

SCEN = Path(__file__).resolve().parents[1] / "scenarios"


def pytest_configure(config):
    if hasattr(config, "workerinput"):  # a pytest-xdist worker
        return
    spec = importlib.util.spec_from_file_location("scenarios_make_session", SCEN / "make.py")
    make = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(make)
    make.write()
