"""Remove every generated file, so the repository starts from a clean slate.

    python util/clean.py             remove them (pixi run clean)
    python util/clean.py --dry-run   only list what would go

What goes (all of it is regenerated by the commands that made it):

* ``out/``: model runs (``model-run --out``), DaCe's build cache
  (``DACE_default_build_folder``) and elaborated RTL (``SNAX_FORGE_HW_OUT``);
* a stray ``.dacecache/`` at the top, from DaCe run outside pixi;
* Python caches: every ``__pycache__/`` below the repository, and the
  ``.pytest_cache/`` and ``.ruff_cache/`` directories;
* Chisel build trees, the same list as ``pixi run chisel-clean``.

What stays: tracked files (``scenarios/`` is checked in, so its scenario
files and ``.npy`` inputs are never touched), the pixi environment
(``.pixi/``), and caches outside the repository (Coursier, pip). The list is
explicit rather than ``git clean -X``, which would also remove ``.pixi/``.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Directories removed whole, relative to the repository root.
DIRS = [
    "out",
    ".dacecache",
    ".pytest_cache",
    ".ruff_cache",
    # as pixi run chisel-clean (out/hw is already under out/)
    "hw/chisel/target",
    "hw/chisel/project/target",
    "hw/chisel/project/project",
    "hw/chisel/test_run_dir",
]

# Never walked into when looking for __pycache__.
SKIP = {".git", ".pixi"}


def targets(root: Path = ROOT) -> list[Path]:
    """Everything that would be removed, existing paths only, in a stable order."""
    found = [root / d for d in DIRS if (root / d).exists()]
    stack = [root]
    while stack:
        d = stack.pop()
        for p in sorted(d.iterdir()):
            if not p.is_dir() or p.is_symlink() or p.name in SKIP or p in found:
                continue
            if p.name == "__pycache__":
                found.append(p)
            else:
                stack.append(p)
    return sorted(found)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--dry-run", action="store_true", help="list, remove nothing")
    args = ap.parse_args(argv)
    paths = targets()
    for p in paths:
        rel = p.relative_to(ROOT)
        if args.dry_run:
            print(f"would remove {rel}")
            continue
        if p.is_dir():
            shutil.rmtree(p)
        else:
            p.unlink()
        print(f"removed {rel}")
    if not paths:
        print("nothing to remove")
    return 0


if __name__ == "__main__":
    sys.exit(main())
